title: skr Linux
author: luhangyu
subtitle: The life of a linux engineer

url: "https://idnw.github.io"
baseurl: "/blog"

footer_only_homepage: true
footer_url: "https://github.com/idnw"
footer_text: "skr Linux"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://github.com/idnw"
